spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql:${DB_URL}
    username: sornrak
    password: 
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 5MB
server:
  port: 8082

  
